### ISSUE TITLE
A question about load_deepfake in utils/Deepfake_utils.py

### ISSUE THREAD

**Issue by defusionalnrt** [heyongxin233/DeTeCtive#2]
On line 64 of file utils/Deepfake_utils.py
```
df = pd.read_csv(file_path, usecols=["text", "label", "src"])
```
But it seems that there're no column "src" on deepfake dataset(downloaded from the link provided on README),only "text" and "label" exists,which causes an error,do I miss anything or is that the dataset provided is incorrect?

**Comment by heyongxin233** [comment]
@defusionalnrt If you directly download the raw data for [DeepFake](https://github.com/yafuly/MAGE), you need to follow the instructions to run the script and obtain different configurations for data splits. The CSV files will include three keys: `text`, `label`, and `src`.

```bash
python3 deployment/prepare_testbeds.py DATA_PATH
```

Alternatively, you can directly download the preprocessed data from this link: [[Preprocessed Data](https://drive.google.com/drive/folders/1FNfSmKFE40FHGBfGjypg_JS2aWO_G6gX)].

**Comment by defusionalnrt** [comment]
@heyongxin233 I downloaded the deepfake zip file from the Preprocessed Data link you provided and it seems that there's only text and label column in those csv files as well.Or do I missed anything?

**Comment by heyongxin233** [comment]
@defusionalnrt Apologies for the oversight that caused the CSV file format to be incorrect. I have now updated the DeepFake dataset, and you can download the corrected version from the following link:[Preprocessed Data](https://drive.google.com/drive/folders/1FNfSmKFE40FHGBfGjypg_JS2aWO_G6gX).

**Comment by defusionalnrt** [comment]
@heyongxin233 yeah it works now,thx :)
