### ISSUE TITLE
KNN vs. MLP classifier

### ISSUE THREAD

**Issue by yanghh2000** [heyongxin233/DeTeCtive#3]
论文中提到使用KNN是因为，在不训练的情况下就能对OOD数据有很好的泛化，但其实是假设有了一些OOD的训练样本，然后存储它们的embedding。我的问题是：这个跟用OOD数据训练MLP classifier有何区别（因为训练分类器本质也是压缩训练数据）？如果OOD数据完全不可见，哪种方法泛化性会比较好呢？作者可以提供一些见解吗。

**Comment by zhangshan233hyx** [comment]
@yanghh2000 解决该任务需要的分界面是复杂的，使用类似于信息检索的方法可以拟合更加复杂分界面，并且KNN基于余弦相似度计算，和我们的训练目标高度一致，MLP相关能力较弱。
根据我们论文中的实验结果，KNN分类的效果更好，OOD数据完全不可见的指标可见论文的表2中 DeTeCtive的第一个指标，如果基于PLM+MLP的指标可以参考表2中的Longformer。

**Comment by yanghh2000** [comment]
Thanks! 确实Table2有展示两者效果的差异
