### ISSUE TITLE
hyperparameter top_K of KNN

### ISSUE THREAD

**Issue by yanghh2000** [heyongxin233/DeTeCtive#4]
请问一下，Table 1上面的四个数据集的结果所用的KNN的Top k都是多少呢

**Comment by heyongxin233** [comment]
@yanghh2000 具体可以参考script/test.sh，可以运行这个脚本得到论文的复现结果

**Comment by xunguo18** [comment]
@yanghh2000 We use K==5 in default, thanks.

**Comment by yanghh2000** [comment]
ok, thanks!
